---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: 'files/patch-*'
      - id: trailing-whitespace
        exclude: 'files/patch-*'
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: check-case-conflict
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      # - id: detect-aws-credentials
      - id: check-docstring-first
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args: [-I, .codespellignore]
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.1.0
#    hooks:
#      - id: detect-secrets
#        args: ['--baseline', '.secrets.baseline']
#        exclude: .*/tests/.*
  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.3.0
    hooks:
      - id: j2lint
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.40
    hooks:
      - id: pymarkdown
        args:
          - -d
          - MD013
          - scan
  - repo: local
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks/issues/683
      # https://github.com/Lucas-C/pre-commit-hooks#forbid--remove-some-unicode-characters
      - id: forbid-unicode-non-breaking-spaces
        name: Detect unicode non-breaking space character U+00A0 aka M-BM-
        language: system
        entry: perl -ne 'print if $m = /\xc2\xa0/; $t ||= $m; END{{exit $t}}'
        files: ""
      - id: remove-unicode-non-breaking-spaces
        name: Remove unicode non-breaking space character U+00A0 aka M-BM-
        language: system
        entry: perl -pi* -e 's/\xc2\xa0/ /g && ($t = 1) && print STDERR $_; END{{exit $t}}'
        files: ""
      - id: forbid-en-dashes
        name: Detect the EXTREMELY confusing unicode character U+2013
        language: system
        entry: perl -ne 'print if $m = /\xe2\x80\x93/; $t ||= $m; END{{exit $t}}'
        files: ""
      - id: remove-en-dashes
        name: Remove the EXTREMELY confusing unicode character U+2013
        language: system
        entry: perl -pi* -e 's/\xe2\x80\x93/-/g && ($t = 1) && print STDERR $_; END{{exit $t}}'
        files: ""
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v26.9.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
