---

roles:
  - src: https://github.com/juju4/ansible-redhat-epel/
    version: main
    name: juju4.redhat_epel
  - src: https://github.com/juju4/ansible-ipsumdump/
    version: main
    name: juju4.ipsumdump
  - name: geerlingguy.nodejs
    src: https://github.com/juju4/ansible-role-nodejs/
    version: devel
